spring:
  liquibase:
    change-log: classpath:db/migration/mainChangelog.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/api_gateway_db
    username: holly
    password: admin
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: client
              uri: lb://client
              predicates:
                - Path=/ec/**
server:
  port: 8082
app:
  security:
    key: HelloIsMyKey322HelloIsMyKey322HelloIsMyKey322HelloIsMyKey322HelloIsMyKey322


