spring:
  liquibase:
    change-log: classpath:db/migration/mainChangelog.yaml
  datasource:
    url: jdbc:postgresql://postgres-db:5432/api_gateway_db
    username: holly
    password: admin322
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
          routes:
            - id: client
              uri: lb://client
              predicates:
                - Path=/ec/**
server:
  port: 8082
app:
  security:
    key: HelloIsMyKey322HelloIsMyKey322HelloIsMyKey322HelloIsMyKey322HelloIsMyKey322
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka


