services:
  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bank_rest_example_db
      - POSTGRES_USER=holly
      - POSTGRES_PASSWORD=admin322
    ports:
      - 5432:5432